apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: orders-dlq
  namespace: kafka-demo
  labels:
    strimzi.io/cluster: demo-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: "86400000"
    cleanup.policy: delete
