apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka-demo
resources:
  - producer-imagestream.yaml
  - consumer-imagestream.yaml
  - producer-buildconfig.yaml
  - consumer-buildconfig.yaml
  - producer-deployment.yaml
  - consumer-deployment.yaml
  - producer-service.yaml
  - consumer-service.yaml
