spring:
  application:
    name: producer
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:demo-kafka-kafka-bootstrap:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: INFO
